name: Vision
description: A Mobile app for blind people
full_description: 'A Mobile App for blind people that makes their life better by givivng them support from volunteers and money detection system<br>
<br>With a lot of features:
<br>- Money Detection.
<br>- Video Calls.
<br>- Easy SignUp with google.'
android: ""
iOS: ""
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
